server:
interface: 0.0.0.0
access-control: 127.0.0.0/8 allow
access-control: 192.168.3.0/24 allow
auth-zone:
        name: "smlnk.spb.ru"
        for-downstream: yes
        for-upstream: yes
        zonefile: "/usr/local/etc/unbound/smlnk.spb.ru"

remote-control:
control-enable: yes
control-interface: 127.0.0.1
control-use-cert: no
