; Zone file for sk.spb.ru
; Generated by IO Tools DNS Zone File Generator
; https://iotools.cloud/tool/dns-zone-file-generator/
;
$TTL 3600
$ORIGIN smlnk.spb.ru.

@       IN      SOA     fbsd.smlnk.ru. ss.ss.ru. (
        3       ; Serial
        3600    ; Refresh
        900     ; Retry
        1209600 ; Expire
        86400   ; Minimum TTL
)

; DNS Records
@       IN      A       192.168.3.172
git     IN      A       192.168.3.172
